# Generated by Django 4.1.7 on 2023-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedslot',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
